### PR TITLE
Update pcloudapi.py

### PR DESCRIPTION
**Pull request by lukkie112**
Fix Login Problem to pCloud Account

### CODE REVIEW

**Comment by gdomenici** [comment]
Hi @lukkie112 . Thanks for your PR. I am afraid I cannot merge it as it is, because

1. eapi.pcloud.com is not mentioned anywhere in the PCloud official docs as an official API endpoint. If you Google for that, it's mentioned as the "European endpoint" but it doesn't seem to be official. I wouldnt like to use an undocumented endpoint in the released version of the plugin.
1. But, more importantly, it doesn't seem to work for me. If I try the change you have in your PR, I am unable to authenticate.

What do you suggest?

Kind regards,

Guido

**Comment by lukkie112** [comment]
Hi! 
It is so, that my fix is ONLY for Users with EU Sever Location, as I
The eAPI I have read out with developer tools on Firefox an it works fine for me
Perhaps you can do a fix for booth Api's? 

It is the same when i I have to use WebDav on some Explorer Tools on Android. There i have too use eWebDav instead of Webdav (this information is fom customer service)

**Comment by gdomenici-verimatrix** [comment]
> Hi!
> It is so, that my fix is ONLY for Users with EU Sever Location, as I
> The eAPI I have read out with developer tools on Firefox an it works fine for me
> Perhaps you can do a fix for booth Api's?
> 
> It is the same when i I have to use WebDav on some Explorer Tools on Android. There i have too use eWebDav instead of Webdav (this information is fom customer service)

Hi @lukkie112 

Thanks for your clarification. In that case, the PR is OK, but we also need to add a setting to the settings screen to let users choose which of the two servers (api or eapi) do they want to use. If you know how to do that, it would be awesome if you also added some code to expose this setting. Would you like to help with that?

Kind regards,

Guido

**Comment by lukkie112** [comment]
Hi!
I myself can not help to fix this problem. But I asked a Developer Friend for help. He has an idea and is working for the fix

**Pull request closed without merging**
