### PR TITLE
Modification for European login and KODI 18.9

### PR DESCRIPTION
**Pull request by Copinmalin**
This reverts commit 02a2f8364dd91b853da0bd8afa9b1fbeddb60210.

### CODE REVIEW

**Comment by gdomenici** [comment]
Hi @Copinmalin ,

Thanks for the pull request,

In fact, I already implemented this as part of this commit: https://github.com/gdomenici/plugin.video.pcloud-video-streaming/commit/cefc70558697bc3562fff233ae6bc7a2ca7590dc. Version 1.5.1 of the plugin (available in the Releases section, and in the official PCloud repo) allows you to chose the "eapi" endpoint as part of the settings. Thus the change in this PR is no longer necessary.

Kind regards,

Guido

**Comment by Copinmalin** [comment]
Hello,

Thanks for your replie.

But, when you have a RPI3 you can't install it and so you dont have choice.

It's why i'm asking for this solution.

Do I wrong ?

BR


Le 27 septembre 2021 21:09:58 GMT+02:00, Guido Domenici ***@***.***> a écrit :
>Hi @Copinmalin ,
>
>Thanks for the pull request,
>
>In fact, I already implemented this as part of this commit: https://github.com/gdomenici/plugin.video.pcloud-video-streaming/commit/cefc70558697bc3562fff233ae6bc7a2ca7590dc. Version 1.5.1 of the plugin (available in the Releases section, and in the official PCloud repo) allows you to chose the "eapi" endpoint as part of the settings. Thus the change in this PR is no longer necessary.
>
>Kind regards,
>
>Guido
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gdomenici/plugin.video.pcloud-video-streaming/pull/40#issuecomment-928190290
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gdomenici** [comment]
Hi @Copinmalin ,

> when you have a RPI3 you can't install it and so you dont have choice.

I suppose RPI3 is a Raspberry PI 3.

Sorry, I am not sure I understand. Can you elaborate on that? You mean you can't install the ZIP from https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/tag/1.5.1 or from the Kodi official plugin repo?

**Comment by Copinmalin** [comment]
Hello,

Exactly,

The is "the dependency on xbmc.python version 3.0.0 could not be satisfied"

I'm with librelec 9.2.7,  and RPI2.arm (not RPI3 sorry)

BR

Le 28 septembre 2021 14:01:41 GMT+02:00, Guido Domenici ***@***.***> a écrit :
>Hi @Copinmalin ,
>
>> when you have a RPI3 you can't install it and so you dont have choice.
>
>I suppose RPI3 is a Raspberry PI 3.
>
>Sorry, I am not sure I understand. Can you elaborate on that? You mean you can't install the ZIP from https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/tag/1.5.1 or from the Kodi official plugin repo?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gdomenici/plugin.video.pcloud-video-streaming/pull/40#issuecomment-929122019
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gdomenici** [comment]
> 
> Hello, Exactly, The is "the dependency on xbmc.python version 3.0.0 could not be satisfied" I'm with librelec 9.2.7, and RPI2.arm (not RPI3 sorry) BR Le 28 septembre 2021 14:01:41 GMT+02:00, Guido Domenici ***@***.***> a écrit :
> Hi @Copinmalin , > when you have a RPI3 you can't install it and so you dont have choice. I suppose RPI3 is a Raspberry PI 3. Sorry, I am not sure I understand. Can you elaborate on that? You mean you can't install the ZIP from https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/tag/1.5.1 or from the Kodi official plugin repo? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#40 (comment)](https://github.com/gdomenici/plugin.video.pcloud-video-streaming/pull/40#issuecomment-929122019)
> -- Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

Hi @Copinmalin 

OK, I understand. It's because the plugin now only supports Kodi Matrix (19.x) and above, whereas that Kodi version isn't available on the Pi (at least I don't think so).

Tell you what, I'll try one thing: I'll try and backport the new setting - that allows you to choose between the "api" and the "eapi" endpoint - to plugin version 1.4.2, which supports Kodi Helix (14.x). Not sure it will succeed, but will inform here. Stay tuned.

Kind regards,

Guido

**Comment by gdomenici** [comment]
Created https://github.com/gdomenici/plugin.video.pcloud-video-streaming/issues/42 for that.

**Comment by gdomenici** [comment]
Hi @Copinmalin 

I created [release 1.4.3](https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/tag/1.4.3) for that. I couldn't test it because I dont have an old Kodi version handy, but if you do that you should see that it runs on older Kodi versions, and it has the new setting allowing you to choose the eapi endpoint.

Kind regards,

Guido

**Comment by Copinmalin** [comment]
Many thanks @gdomenici, now I can install app, and choose eapi... Perfect

So the problem now is my login doesn't work :-( 
Error log if it can help :
 
2021-10-03 18:35:08.164 T:894956416    INFO: Python interpreter stopped
2021-10-03 18:35:08.164 T:947909504   DEBUG: Calling https://eapi.pcloud.com/getdigest...
2021-10-03 18:35:08.164 T:894956416   DEBUG: Thread LanguageInvoker 894956416 terminating
2021-10-03 18:35:08.168 T:1631474560   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Input.OnInputFinished  - data: null
2021-10-03 18:35:08.566 T:947909504   DEBUG: Calling https://eapi.pcloud.com/userinfo...
2021-10-03 18:35:08.956 T:947909504   ERROR: ERROR: cannot logon to pCloud: Error calling userinfo: Unknown error
2021-10-03 18:35:08.957 T:947909504    INFO: CPythonInvoker(571, /storage/.kodi/addons/plugin.video.pcloud-video-streaming/addon.py): script aborted
2021-10-03 18:35:08.958 T:947909504   DEBUG: onExecutionDone(571, /storage/.kodi/addons/plugin.video.pcloud-video-streaming/addon.py)
2021-10-03 18:35:08.973 T:947909504    INFO: Python interpreter stopped
2021-10-03 18:35:08.973 T:947909504   DEBUG: Thread LanguageInvoker 947909504 terminating
2021-10-03 18:35:08.984 T:984802176   ERROR: GetDirectory - Error getting plugin://plugin.video.pcloud-video-streaming/?content_type=image
2021-10-03 18:35:08.985 T:984802176   DEBUG: Thread waiting 984802176 terminating

**Comment by gdomenici** [comment]
The key line seems to be "2021-10-03 18:35:08.956 T:947909504 ERROR: ERROR: cannot logon to pCloud: Error calling userinfo: Unknown error".

I am not sure if you have access to the Pi's file system, but if so please try deleting the following directory:

/storage/.kodi/userdata/addon_data/plugin.video.pcloud-video-streaming

and then try opening the plugin again. What i suspect is that perhaps in the data directory an old token was persisted that is no longer valid, and by deleting that directory you force recreation of the token.

**Comment by Copinmalin** [comment]
Hi,
Sorry but it doesn't work : 

Pcloud error

Maybe another idea ?

**Comment by gdomenici** [comment]
Hi @Copinmalin 

Thanks for trying. In fact, no other idea. The ironic thing is that i created myself a EU-based account to test using EAPI and, for me, it just works!

What I have done is, i have created a version with extra debug info, [1.4.4](https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/tag/1.4.4). If you please try that and send me the log, the "Unknown error" line should also show a numeric error code. Maybe that will give us further clues.

Kind regards,

Guido

**Comment by Copinmalin** [comment]
Hello,

I don't find log ?

Where it could be save ?

**Comment by gdomenici** [comment]
Hey @Copinmalin 

It should be in the same place where you got all previous logs... /storage/.kodi/kodi.log. Could you not find it there?

**Comment by Copinmalin** [comment]
Hey,

I found in /temp 👍 


May be it can help you

**Comment by gdomenici** [comment]
Thanks for that @Copinmalin 

In the meantime i managed to reproduce your error, by running a LibreElec 9.2.6 virtual machine. It is true that the error occurs only on that specific LibreElec (9.2.6)/Kodi (18.9.0) distro. At least now i can investigate further without needing to ask you additional info. Stay tuned.

**Comment by gdomenici** [comment]
Hey @Copinmalin 

I figured out the issue. It is that you (very likely) have 2-factor authentication (2FA) enabled on PCloud. Alas, unfortunately PCloud does not support 2FA from third-party applications -- only from their first-party ones 😟.

See [my comment on this ticket](https://github.com/gdomenici/plugin.video.pcloud-video-streaming/issues/32#issuecomment-763414931), which is when this problem was first raised. What I'll do is, I'll update the README on the plugin to make it clear that the plugin will never work with 2FA until PCloud changes their policy. Sorry.

To be clear: the only way to make the plugin work is to disable 2FA.

Kind regards,

Guido

**Comment by Copinmalin** [comment]
OK I understand, many thanks for your help and time passed to find error.
BR

**Pull request closed without merging**
